apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: fabricioveronez/jornada-kubernetes-api:v4
        ports:
        - containerPort: 8080
        resources: 
          limits:
            memory: 60Mi
            cpu: 500m
          requests:
            memory: 40Mi
            cpu: 250m   
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongo-service:27017/admin
